name: tmdb-app

on:
  push:
    branches: ["releases"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: baixar código
        uses: actions/checkout@v4

      - name: instalar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: instalar dependências
        run: npm ci

      - name: rodar testes
        run: npm test

  build:
    needs: teste
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: usa o Node js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: instala dependencias
        run: npm install

      - name: Instalar Expo CLI
        run: npm install -g expo-cli

      - name: cria a .env
        run: |
          echo "EXPO_PUBLIC_TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" > .env

      - name: exporta
        run: npx expo export:web

      - name: desvia do jekyll
        run: touch dist/.nojekyll

      - name: Upload do artefato
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Baixar APK
        uses: actions/download-artifact@v4
        with:
          name: app-release

      - name: Criar GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          files: app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}